cargo-features = ["edition2024"]

[package]
name = "catch22"
version = "0.1.0"
edition = "2024"

[dependencies]
rustfft = "6.3.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "features"
harness = false

[profile.release]
lto = true
codegen-units = 1
